default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mydatabase
  username: kidd
  password: eunbeb
  host: localhost
  port: 5432 # Make sure this matches your PostgreSQL port

test:
  <<: *default
  database: mydatabase
  username: kidd
  password: eunbeb
  host: localhost
  port: 5432 # Make sure this matches your PostgreSQL port

production:
  <<: *default
  database: mydatabase
  username: kidd
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432 # Make sure this matches your PostgreSQL port
